version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Rameen-Mahmood"
    versioning-strategy: "increase-if-necessary"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"